### ISSUE TITLE
Getting 'This callback was already called' message

### ISSUE THREAD

**Issue by angleman** [apiaryio/s3-streaming-upload#10]
Doing 495MB stream upload, going great, got to Uploading 94, then the uploading events paused for a few minutes; however, the network showed still uploading at 2Mb/s so all appeared well, then started getting "This callback was already called, WTF; chunk &lt;Buffer ...&gt;" messages. Even with these messages, data continues to upload. Thoughts?

**Comment by abtris** [comment]
I released new version 0.2.0 this is based on new AWS SDK 2.x. Please, test if problem still exists.
