### ISSUE TITLE
v4 auth mechanism

### ISSUE THREAD

**Issue by AndrewGrachov** [apiaryio/s3-streaming-upload#26]
`The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256`

When using frankfurt DPC. Frankfurt DPC does not support V2 auth

**Comment by abtris** [comment]
I think this is fixed in AWS SDK [2.1.2](http://aws.amazon.com/releasenotes/SDK/JavaScript/6936842197847930). We have update to 2.1.7 in #27

**Comment by abtris** [comment]
Can you test with new version?

**Comment by abtris** [comment]
I released new version 0.2.0 this is based on new AWS SDK 2.x. Please, test if problem still exists.

**Comment by nickdima** [comment]
In case someone has this problem, you have to pass the AWS region in which you set up the bucket.
`region` is a supported option but not specified in the README.

**Comment by Almad** [comment]
Good point, docs shall be fixed. PRs welcome :)
