### ISSUE TITLE
Event names are inconsistent with Streams interface

### ISSUE THREAD

**Issue by mojodna** [apiaryio/s3-streaming-upload#30]
As a [`Writable`](http://nodejs.org/api/stream.html#stream_class_stream_writable) stream, I would expect a `finish` event in place of `completed` (also fired when errors occur, providing a single event to hang cleanup tasks on) and `error` in place of `failed`.

**Comment by Almad** [comment]
Fair point.

**Comment by abtris** [comment]
Not applicable on current version.
