### ISSUE TITLE
Keys have 0 size

### ISSUE THREAD

**Issue by GeoffreyPlitt** [apiaryio/s3-streaming-upload#35]
I uploaded a buch of data, but the size is always 0 bytes after "completed" event.

**Comment by abtris** [comment]
I released new version 0.2.0 this is based on new AWS SDK 2.x. Please, test if problem still exists.

**Comment by GeoffreyPlitt** [comment]
I'm using 0.2.0 now, and the input stream does not get consumed at all. I used debug:true and there's no output, how do I get debug output?

**Comment by GeoffreyPlitt** [comment]
Can you publish a working test?

**Comment by GeoffreyPlitt** [comment]
Also, at https://github.com/apiaryio/s3-streaming-upload/blob/master/src/uploader.coffee#L26, it looks like your minimum size is 5mb??

**Comment by abtris** [comment]
1) debug turn on console.log from event "httpUploadProgress", you can see upload progress
2) we have integrations tests https://github.com/apiaryio/s3-streaming-upload/blob/master/test/integration/chunk-test.coffee and https://github.com/apiaryio/s3-streaming-upload/blob/master/test/integration/upload-test.coffee 
These tests need credentials to S3 you have to setup environment properties `AWS_S3_ACCESS_KEY`, `AWS_S3_SECRET_KEY`, `AWS_S3_TEST_BUCKET` to successful run
3) [5MB is minimal chunk size](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#minPartSize-property), this is used for queue if you upload file bigger than 5MB, small files are in one chunk as in this test https://github.com/apiaryio/s3-streaming-upload/blob/master/test/integration/upload-test.coffee
