### ISSUE TITLE
Not working with https enabled

### ISSUE THREAD

**Issue by hitubansal123** [apiaryio/s3-streaming-upload#47]
i have secure ssl enabled on website. this stops working.  

No Error .

**Comment by abtris** [comment]
Can you add example of using? I'm not sure how can SSL have impact to NodeJS library.

**Comment by hitubansal123** [comment]
Hello 
I have use follwing code to start the server

var secureServer = https.createServer(sslOptions,app).listen(443, function(){
  
    console.log("Sever Started");
});

And 


upload = new Uploader({
  // credentials to access AWS
  accessKey:  config.aws.accessKey,
  secretKey:  config.aws.secretKey,
  bucket:     'bibliohivepdf',
  objectName: "pdf1/"+filename,
  stream:     fileReadStream,
  objectParams: {
    ACL: 'public-read'
  },
  debug:      true
});

upload.send(function (err) {
  if (err) {
    console.log("Errro"+err);
    console.error('Upload error' + err);
  } else {
   console.log("Sucessfull");
  }
});


This code is working fine. if i run on 80 port instead of 443

**Comment by abtris** [comment]
Thanks, I look into.

**Comment by hitubansal123** [comment]
Sure,  i am waiting for your response on the same.

**Comment by hitubansal123** [comment]
Do i need to change any settings for SSL on S3 as well, becuase it doesnt error out even.

**Comment by abtris** [comment]
I use [aws s3 library](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html) this cannot be relevant with upload library. This isn't anything relevant with your server.

**Comment by hitubansal123** [comment]
So what you suggest for the same. how i can debug it more

**Comment by hitubansal123** [comment]
I put wrong Secret key . Even it doesn't through error. It just to inform you. may be you can give me an idea more .

**Comment by hitubansal123** [comment]
We need to  set ssl options: true or false.  it will work.
