### ISSUE TITLE
Question : Can be run on EC2 instance in context of IAM role?

### ISSUE THREAD

**Issue by tbenade** [apiaryio/s3-streaming-upload#49]
Hi,

Having a look at this code https://github.com/apiaryio/s3-streaming-upload/blob/master/src/uploader.coffee#L10 it appears the requirement to have credentials or STS session token is mandatory. This negates any possibility of running this code on an EC2 instance within the context of an IAM role.

http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Credentials_from_IAM_Roles_for_EC2_Instances

Am I correct? Pondering a pull request but hoping you could confirm my suspicions.

Thanks

**Comment by mousavian** [comment]
Having this can be useful.
To provide more context on this issue, [there are few ways](https://github.com/aws/aws-sdk-js/tree/4c768539749f4c3056d30a58fa0ddba28df5504c/lib/credentials) to get credentials and get access to aws resources. [EC2MetadataCredentials Class](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2MetadataCredentials.html) provides a way to communicate with Metadata API from an EC2 to fetch a temporary credentials without having an explicit/static keys and secret. 
Hence I also think providing accessKey & secretKey should be optional.
