### ISSUE TITLE
add support for customizable S3 endpoint

### ISSUE THREAD

**Issue by hulbert** [apiaryio/s3-streaming-upload#53]
Adding [the ability to configure the endpoint](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#endpoint-property) would enable using this library with "fake S3" implementations for testing as well as S3 compatible implementations like Riak CS.

**Comment by abtris** [comment]
Good point.  I can add this feature. I just need the test for it. Do you recommend library not just "fake S3" for testing here in the library?

**Comment by abtris** [comment]
Solved by `service` parameter you can add `aws.S3` where you can use custom endpoint. Example using with OCI.
